### ISSUE TITLE
CI: add publishing to maven central

### ISSUE THREAD

**Issue by jbordeau** [Enovea/s2-geometry-kotlin#2]
[First setup OSSRH](https://central.sonatype.org/publish/publish-guide/):

Documentations for github actions:
https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository-and-github-packages
https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven
https://github.com/jonashackt/github-actions-release-maven

Only on release (create tag)

**Comment by fmeurisse** [comment]
New issue opened in Sonatype Jira for groupId creation.
